### ISSUE TITLE
bug in remote url data

### ISSUE THREAD

**Issue by Nodir-Bek** [dropzone-ui/react#114] opened 2021-10-28 11:40 UTC
The url information on the server does not appear in the preview!
![image](https://user-images.githubusercontent.com/73289991/139248454-1266b1e8-7e4d-48af-9d61-e4fa46a25f9f.png)
![image](https://user-images.githubusercontent.com/73289991/139248622-ebaf9a20-a1f7-407f-a1f8-941f634ce9f5.png)

**Comment by Nodir-Bek** [comment] 2021-10-30 06:54
In my current project, I use useFormik to store data, when images are uploaded to dropzone, they are queried in the backend and uploaded to the server. then the respone returns and the urls of the images in this response return. I equate the urs that come to me to the state in useFormik and send them to FileItem as props. (I checked that the url worked in the browser !!!). but the results are not visible in the project. I will send you my code.
import React from 'react';
import { Dropzone, FileItem, FullScreenPreview } from '@dropzone-ui/react';
import { useStyles } from './style';

export default ({ files = [], onDelete, updateFiles, handleSee, imageSrc, index }) => {
  const classes = useStyles();
  return (
    <Dropzone
      className={classes.dropzone}
      view="list"
      onChange={(e) => updateFiles(e, index)}
      value={files}
      maxFiles={15}
      footer={false}
      maxFileSize={2998000}
      accept=".png,.jpg,image/*"
    >
      {files.map((file, index) => (
        <FileItem
          key={`${index + 1}`}
          {...file}
          onDelete={onDelete}
          onSee={handleSee}
          preview
          hd
          valid
        />
      ))}
      <FullScreenPreview
        imgSource={imageSrc}
        openImage={imageSrc}
        onClose={() => handleSee(undefined)}
      />
    </Dropzone>
  );
};

**Comment by JinSSJ3** [comment] 2021-10-30 18:13
Hi @ Nodir-Bek, as far as we understood given your explanation and code, the issue is on the `<FileItem />` component is because you are giving to it an url (a string prop) instead of a `File` object.
`{... file}` is equivalent to give the following props: {`id`, `file`,  `valid`, `uploadStatus`}.


So far, FileItem component is not rendered if you don´t provide the `file` prop as a valid `File` instance. Other thing is that there is no url prop yet. So, if you send `url` prop it will not affect the render process.

One way to solve this issue is to create a `File` object instance given the string url or to keep the file instances used to upload to the server.

This is a bit funny, because we were already implementing :milky_way: :hammer: more use cases and one of them is to provide a way to show directly an image :framed_picture: in the FileItem component through a prop like  `url`.

Tell us, have we understood correctly you issue? If not, we are open to help you, so please, specify more the issue. If yes, we'll try to release this new feature as fast as possible, maybe by the end of today or tomorrow. 
Also, if the alternative we gave to you was enough please let us know.

**Comment by JinSSJ3** [comment] 2021-11-01 16:58
Hi @Nodir-Bek , just in case, there is a new version in wich FileItem can render directly an image preview through `imageUrl` prop. 

When this prop is given, File Item will avoid reading the file and will show the image from the url (can be web server url or a string representation like base64).

However a `File` object instance in still required in order to preserve consistency. If you dont have the file object or don´t want to use one, you can use a synthetic file creator function that comes in this new version. We use that in tests to create "fake" file objects, just giving file name, size and mime type.

An example of this use case can be found here:

https://codesandbox.io/s/imageurl-to-fileitem-m4801?file=/src/App.js

**Comment by Nodir-Bek** [comment] 2021-11-02 04:29
🤓Yes Thanks, may I have a problem with my Cods because I work in Junior
Level. I am happy if the information I sent to be a solution to some
problem. I wish the team good luck!

пн, 1 нояб. 2021 г. в 21:59, Jin Jose Manuel ***@***.***>:

**Comment by JinSSJ3** [comment] 2021-11-02 04:50
Awsome!, 🎉 

we are happy to hear that.
👀 If you get stuck again or have any doubt, just open an issue again. 
We'll be happy to help you. 😄 

For now I´ll close this issue.

**Closed by JinSSJ3** 2021-11-02 04:50 UTC
Labels: good first issue
